config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
  get 'users/:id/profile', to: 'users#profile', as: 'user_profile'
  resources :posts do
    resources :comments, only: [:new, :create]
  end
  resources :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
    has_many :posts_tags
    has_many :tags, through: :posts_tags
    has_many :comments

    validates :title, presence: true
    validates :content, presence: true
    validates :user_id, presence: true
    validates :answers_count, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validate :set_published_at

    private
        def set_published_at
            self.published_at = Time.now unless published_at.present?
        end
end

app/models/posts_tag.rb
class PostsTag < ApplicationRecord
    belongs_to :post
    belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :posts_tags
    has_many :posts, through: :posts_tags

    validates :name, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    has_many :posts
    has_many :comments

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true
    validates :password, presence: true, length: { minimum: 6 }, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_comment, only: %i[show edit update destroy]
  before_action :just_user, only: [:edit, :update, :destroy]

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    if params[:post_id]
      @comment.post_id = params[:post_id]
    end
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to comment_url(@comment), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :post_id)
  end

  def just_user
    @comment = Comment.find(params[:id])
    redirect_to comments_path, notice: "Not authorized to edit this comment" unless @comment.user == current_user
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :authenticate_user!, except: [:index, :show]
  before_action :just_user, only: [:edit, :update, :destroy]

	def index
		@posts = Post.all
	end

	def show
		@post = Post.find(params[:id])
	end

	def new
		@post = Post.new
		puts "session: #{session[:user_id]}"
	end

  def create
    puts "params: #{params}"
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

	def edit
		@post = Post.find(params[:id])
	end

  def update
    post = Post.find_by(id: params[:id])

    if post.update(post_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end

	private

	def post_params
		params.require(:post).permit(:title, :content, :user_id, :answers_count)
	end

  def just_user
    post = Post.find(params[:id])
    unless current_user.id == post.user_id
      redirect_to posts_path, alert: 'You are not authorized to modify this post.'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def profile
    @user = User.find_by(id: params[:id])
    if @user.nil?
      redirect_to root_path, alert: "User not found"
    else
      @posts = @user.posts
      @comments = @user.comments
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with(model: @comment, local: true) do |form| %>
  <div class="form-group mb-3">
    <%= form.label :body %>
    <%= form.text_area :body, class: "form-control", required: true %>
  </div>

  <% if @comment.new_record? %>
    <% if params[:post_id] %>
      <%= form.hidden_field :post_id, value: params[:post_id] %>
    <% else %>
      <div class="form-group mb-3">
        <%= form.label :post_id %>
        <%= form.collection_select :post_id, Post.all, :id, :title, {prompt: "Select a post"}, {class: "form-control"} %>
      </div>
    <% end %>
  <% else %>
    <div class="form-group mb-3">
      <%= form.label :post_id %>
      <%= form.collection_select :post_id, Post.all, :id, :title, {prompt: "Select a post"}, {class: "form-control", disabled: true} %>
    </div>
  <% end %>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<%= link_to 'New Comment', new_comment_path, class: 'btn btn-primary' %>


<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th>Post</th>
      <th> Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><a href="/users/<%= comment.user_id %>"><%= comment.user_id %></a></td>
        <td><a href="/posts/<%= comment.post_id %>"><%= comment.post_id %></a></td>
        <td>
          <%= link_to 'Show', comment, class: 'btn btn-info' %>
          <%= link_to 'Edit', edit_comment_path(comment), class: 'btn btn-warning' %>
          <%= link_to 'Destroy', comment, data: { turbo_confirm: 'Are you sure?', turbo_method: "delete" }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

app/views/comments/show.html.erb
<h1>Showing comment</h1>

<p><strong>Body:</strong></p>
<p><%= @comment.body %></p>

<p><strong>User:</strong></p>
<p><a href="/users/<%= @comment.user_id %>"><%= @comment.user_id %></a></p>

<p><strong>Post:</strong></p>
<p><a href="/posts/<%= @comment.post_id %>"><%= @comment.post_id %></a></p>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment), class: "btn btn-warning" %>
  <%= link_to "Back to comments", comments_path, class: "btn btn-primary" %>
  <%= link_to "Destroy this comment", @comment , data: { turbo_confirm: 'Are you sure?', turbo_method: "delete" }, class: "btn btn-danger" %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Y</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/posts">Post</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/comments">Comment</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'My Profile', user_profile_path(current_user) %>
          </li>
        <% end %>
      </ul>
    <ul class="navbar-nav">
      <% if user_signed_in? %>
        <li class="nav-item">
      <%= link_to "Logout", destroy_user_session_path, class: "nav-link", data: 
  { turbo_method: :delete } %>
        </li>
      <% else %>
        <li class="nav-item">
      <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
      <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
      <% end %> 
    </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>YApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: post, local: true do |form| %>
  <div class="form-group mb-3">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control", required: true %>
  </div>

  <div class="form-group mb-3">
    <%= form.label :content %>
    <%= form.text_area :content, class: "form-control", required: true %>
  </div>

    <div class="form-group mb-3">
      <%= form.label :Username %>
      <%= form.text_field :current_user, value: current_user.name, class: "form-control", readonly: true %>
    </div>

  <%= form.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/posts/_post.html.erb
<div class="col-3">  
  <div class="card" style="width: 18rem;">
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <h6 class="card-subtitle mb-2 text-muted"><%= post.user.name %></h6>
      <p class="card-text"><%= post.content.truncate 50 %></p>
      <p class="card-text">Comments: <%= post.comments.count %></p>
      <%= link_to 'View', post, class: 'card-link btn btn-primary' %>
      <%= link_to 'Edit', edit_post_path(post), class: 'card-link btn btn-warning' %>
    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<h1> Edit Post </h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% if user_signed_in? %>
  <%= link_to "New Post" ,new_post_path, class: "btn btn-primary mb-3" %>
<% end %><div class="row">

  <%= render partial: 'post', collection: @posts %>
</div>

app/views/posts/new.html.erb
<h1> New Post </h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h2>Author: <%= @post.user.name %></h2>
<p><%= @post.content %></p>
<%= link_to 'Edit', edit_post_path(@post), class: 'btn btn-warning' %>
<%= link_to 'Back', posts_path, class: 'btn btn-primary' %>
<%= link_to 'New Comment', new_post_comment_path(@post), class: 'btn btn-primary' %>
<%= link_to 'Destroy', @post, turbo_confirm: 'Are you sure?', method: :delete, class: 'btn btn-danger' %>


<h2>Comments</h2>

<table class="table">
  <thead>
    <tr>
      <th>Body</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post.comments.each do |comment| %>
      <tr>
        <td><%= comment.body %></td>
        <td><%= comment.user.name %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/profile.html.erb
<div class="container mt-5">
  <% if @user %>
    <div class="row">
      <div class="col-md-6">
        <h1><%= @user.name %>'s Profile</h1>
        <p><strong>Email:</strong> <%= @user.email %></p>
      </div>
    </div>

    <div class="row mt-4">
      <div class="col-md-6">
        <h2>Posts</h2>
        <% if @posts.any? %>
          <ul class="list-group">
            <% @posts.each do |post| %>
              <li class="list-group-item">
                <strong>Title:</strong> <%= link_to post.title, post %><br>
                <strong>Content:</strong> <%= post.content %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>This user hasn't created any posts yet.</p>
        <% end %>
      </div>

      <div class="col-md-6">
        <h2>Comments</h2>
        <% if @comments.any? %>
          <ul class="list-group">
            <% @comments.each do |comment| %>
              <li class="list-group-item">
                <strong>Post:</strong> <%= link_to comment.post.title, comment.post %><br>
                <strong>Comment:</strong> <%= comment.body %>
              </li>
            <% end %>
          </ul>
        <% else %>
          <p>This user hasn't created any comments yet.</p>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="alert alert-danger" role="alert">
      User not found
    </div>
  <% end %>
</div>